name: Build
on:
  workflow_dispatch:
    inputs:
      package_name:
        description: "Package name of the game:"
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: '11'   # Gradle/AGP가 17을 요구하면 '17'로 바꾸세요.
          cache: gradle

      - name: Build module
        env:
          PKG: ${{ github.event.inputs.package_name }}
        run: |
          chmod +x ./gradlew
          # 모듈 설명에 패키지명 주입
          sed -i "s/moduleDescription = \"/moduleDescription = \"(${PKG}) /g" module.gradle
          # 대상 패키지명 치환
          sed -i "s/com.game.packagename/${PKG}/g" module/src/main/cpp/game.h
          ./gradlew :module:assembleRelease

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: zygisk-il2cppdumper
          path: out/magisk_module_release/
